# Generated by Django 4.2.7 on 2023-12-04 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('F2FarmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerproductitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sellerorders',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='sellerorders',
            name='seller_product',
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='F2FarmApp.product'),
        ),
        migrations.AddField(
            model_name='sellerorders',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='F2FarmApp.customer'),
        ),
        migrations.DeleteModel(
            name='SellerProduct',
        ),
        migrations.DeleteModel(
            name='SellerProductItem',
        ),
    ]
