# Generated by Django 4.2.7 on 2023-12-04 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('F2FarmApp', '0003_remove_sellerorders_product_sellerorders_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='F2FarmApp.sellercart'),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='F2FarmApp.sellercart'),
        ),
    ]
