# Generated by Django 4.2.7 on 2023-12-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F2FarmApp', '0004_alter_sellercartproduct_cart_alter_sellerorders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercartproduct',
            name='grade',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
