# Generated by Django 4.2.7 on 2023-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F2FarmApp', '0005_sellercartproduct_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Pickup', 'Out for Pickup')], max_length=50, null=True),
        ),
    ]
