# Generated by Django 4.2.7 on 2023-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F2FarmApp', '0006_alter_sellerorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercartproduct',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
